name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python-tests:
    name: Python tests (pytest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install dependencies (runtime + dev)
        run: |
          pip install -e .
          pip install -e . --group dev

      - name: Run pytest
        run: pytest

  docker-test-stage:
    name: Docker build (test stage)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test stage (runs pytest inside Dockerfile)
        run: docker build --target test -t devops-app:test ./app
